title:            Sahat Yalkabov
description:      "Full-Stack JavaScript Developer"
disqus_shortname: sahat
url:              http://sahatyalkabov.com
logo:             js.jpg

owner:
  name:           Sahat Yalkabov
  bio:            "I'm a full-stack JavaScript developer from NYC. Hacker School (Summer 2014). CCNY Class of 2014."
  email:          sahat@me.com
  twitter:        EvNowAndForever
  facebook:       NeverSleepNeverDie
  github:         sahat
  linkedin:       sahatyalkabov
  instagram:      13reasons
  google_plus:    +SahatYalkabov

# Links to include in top navigation
# For external links add external: true
links:
  - title: Projects
    url: /projects
  - title: GitHub Profile
    url: https://github.com/sahat
    external: true

timezone:    America/New_York
future:      true

highlighter: pygments

permalink:   /:categories/:title/

gems: [jekyll-paginate]
paginate: 1000
paginate_path: "page:num"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  input: GFM
  syntax_highlighter: rouge

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
